### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by farhadkzm** [SmartLearning/smart-learning#1]
As a user
I want to be able to sign up with my basic profile details
So that I can get registered to the system

**Comment by faridamozg** [comment]
Confirmation email not sent.

**Comment by farhadkzm** [comment]
@faridamozg when you find an issue, please move the card to In Dev, it means the card is most priority task for the developer and he should work on this card first.

**Comment by farhadkzm** [comment]
Found bugs:

- The activation email template and activation link need to be changed as follows:
  - [ ] Email subject: **Please verify your email!**
  - [ ] Email Sender name: **Smart Learning**
  - [ ] Activation link in the email test: The link is invalid, it points to localhost. 
  - [ ] Text of the activation link is the user's name which needs to change to **Account Activation Link**
  - [ ] At the end of email's text, right after Regards, World Team should change to Smart Learning Team
- [ ] Sign Up form title should change from ~~New User~~ to **Create an account** and with a subtitle of **It's free.**
- [ ] After providing correct user details and hitting Register, it show **Registration saved! Please check your email for confirmation.** which should change to **An activation email has sent to you. Please check your email.**, this text should **NOT** disappear.
- [ ] Sign up form should be removed when we show the text.
