### ISSUE TITLE
Right to Left layout

### ISSUE THREAD

**Issue by ghahramani** [SmartLearning/smart-learning#23]
We need to implement right-to-left layout for Persian language

**Comment by faridamozg** [comment]
تم فارسی کاربردی نداره، ترجیحم اینه کلا تم فارسی نداشته باشیم. هزینه و کار هم کمتر میشه

**Comment by ghahramani** [comment]
بحث اینه که اگه بخوایم بین المللی بزنیم عربی و فارسی راست به چپه حتی هیبری هم راست به چپه

**Comment by farhadkzm** [comment]
به نظر من واسه ام وی پی این نیازی شاید نباشه ولی  بعدا بد نیست داشته باشیم.
@faridamozg
و تسک هایی که فک میکنی مهم هستن رو منتقل رو به ستون تسکهای فرید
