### ISSUE TITLE
Exam component

### ISSUE THREAD

**Issue by farhadkzm** [SmartLearning/smart-learning#7]
This is a general component. We show this component on the first user interaction (When we determine the knowledge level of the user) and also in each term to ensure user has learned the content of that term.

Description of the component:
The component shows 5 to 10 questions per page (this should be configurable).
User can answer the questions (or even leave them unanswered) and click on the Next button on the bottom of the component to go to the next page of questions.
There is no Back button.
On the last page, the Next button changes to Submit button.

**Comment by faridamozg** [comment]
به نظرم باید بتونه برگرده و سوالات قبلیش رو دوباره بررسی کنه یا اونهایی رو نزده بخواد بزنه
